language: node_js
node_js:
  - "10"
before_script:
  - yarn firebase setup:emulators:firestore
  - yarn build
cache: yarn
notifications:
  email: false
  webhooks: "https://ship.freshfox.at/travis/-1001141933878"
