name: Firestore Storage CI

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: '/tmp/google-credentials-sa-node-${{ matrix.node }}-${{ matrix.package }}.json'
    strategy:
      matrix:
        package: [ core, firestore, indexes, function-utils ]
        node: [ 16 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm lerna bootstrap
      - name: Build package
        run: |
          cd packages/${{ matrix.package }}
          pnpm build
      - name: Test package
        env:
          FIRESTORE_EMULATOR_HOST: 'localhost:8080'
        run: |
          cd packages/${{ matrix.package }}
          pnpm test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/${{ matrix.package }}/test-results.xml"
