name: Firestore Storage CI

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ core, firestore, indexes ]
        node: [ 14 ]
    env:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
      GOOGLE_APPLICATION_CREDENTIALS: '/tmp/google-credentials-sa-node-${{ matrix.node }}-${{ matrix.package }}.json'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: modules-cache-${{ matrix.node }}-${{ matrix.package }}
        with:
          path: 'packages/${{ matrix.package }}/node_modules'
          key: ${{ runner.os }}-api-node-modules-${{ matrix.node }}-${{ hashFiles('packages/${{ matrix.package }}/package.json') }}
      - name: Install dependencies
        if: steps.modules-cache-${{ matrix.node }}-${{ matrix.package }}.outputs.cache-hit != 'true'
        run: cd packages/${{ matrix.package }} && yarn install
      - name: Build package
        run: cd packages/${{ matrix.package }} && yarn build
      - name: Prepare tests
        run: |
          cd packages/${{ matrix.package }}
          npm run test:prepare --if-present
      - name: Test package
        run: cd packages/${{ matrix.package }} && yarn test
